### ISSUE TITLE
Reclaiming Moria-Flowing Waters

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#100]
## Description
after prssing the two bottons on the great wheel the dialog flowing water doesn't start
## Base information
* Minecraft version:1.12.2
* Minecraft Forge version:14.23.5.2847
* TolkienCraft II version: 1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
it's not supposed to flow or open anything, just progress the quest line
