### ISSUE TITLE
Brimigak throne room

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#101]
## Description
during the quest "Brimigak's fall II " the dialog Brimigak throne room must be completed but the quest doesn't recognize it and it will not be completed.
## Base information
* Minecraft version:1.12.2
* Minecraft Forge version:14.23.5.284
 TolkienCraft II version:1.12.2-2.0.20
## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
The Quest Brimigak's Fall II is a location quest so should be detecting the ember camp when you return.  If it is not triggering (which happens from time to time with CustomNPC's) you have to move about 32 blocks away then go back for it to detect.  Tested in dev and it is working as intended (doing what I suggested)
