### ISSUE TITLE
Normal Mob Spawning

### ISSUE THREAD

**Issue by bsvdw** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#104]
Hi I'm using this pack on a little server just for my close friends on a randomly generated world and I realized that normal mobs (ie. pigs, zombies, skeletons, etc.) weren't spawning, and couldn't be spawned. Can I change this back to normal and if so how?

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.5.2847
* TolkienCraft II version: 1.12.2-2.0.53

**Comment by GreatOrator** [comment]
Hello,

That is a setting for tolkientweaks - mobs edition.  just change it in the config file and normal mobs will spawn again
