### ISSUE TITLE
Missions book does not appear

### ISSUE THREAD

**Issue by Ayrthwil** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#105]
## Description

My quest book is not showing, the only book I have is the tome akashic. I've tried using the command suggested on the wiki and tried to reset with npc, even so it doesn't work.

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: forge-14.23.5.2847
* TolkienCraft II version: TolkienCraft III-1.12.2-2.0.53

## Crash report
```
No crash reporter
```

**Comment by Ayrthwil** [comment]
An update on events, I can open the quest guide even without the book due to a shortcut, but the unlocked guides are just Wise Leaders and Factions. Is that correct? Another question that arose, should the mini map of the journey map exist forever? I am using the map you have downloaded.

**Comment by teagan75** [comment]
What do you mean the mini map exists forever? The journeymap mini map is persistent and stays on your screen.

**Comment by GreatOrator** [comment]
when you start there should only be a small number of quests to get you going, they help you understand how the pack works, and yes the mini map is persistent
