### ISSUE TITLE
NPC Quests don't want to chat with us

### ISSUE THREAD

**Issue by samche2000** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#107]
## Description

We were 3 players: Mandrin (op), Lilhyum and Abarurnas. We play on gamemode 2 in the dimension of Middle-Earth map only.

After killing 2 Trolls at Trollshaws (chapter 1 : Elladan Quest), we killed the third troll. Lilhyum didn't complete the quest (always 2/3 on Bandrith task). We killed him a second time for her but always uncomplete task. I used the bq_admin command to complete it for her.

Elladan talked to us and ask to go to Barachen. We go to see Barachen but this NPC only say "Hello" to each of us. Since this time, it seems every NPC quest only says "Hello" and don't participate to the quest.
[20200920115315.zip](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/5251421/20200920115315.zip)

## Base information
* Minecraft version : 1.12.2
* Minecraft Forge version : 1.12.2-2847
* TolkienCraft III version : 2.0.53

## Server Environment
CPU : Intel Xeon E5 2Vc
RAM : 8Go DDR
HD  : 35 Go SSD
https://www.ouiheberg.com/hebergement-minecraft (Lapis offer)
3 players simultaneous max

### Mandrin (logs from this client)
cf client_dxdiag.txt attached with this issue

### Abarurnas and Lilhyum

Default config from twitch

## Crash report
```
**Logs are attached with this issue**
```

**Comment by samche2000** [comment]
Correction ingame with command
/noppes quest [remove|finish] player quest

It seems there is a desync betweent betterquesting and customnpc questing. Files in /world/customnpcs/playerdata reveal the error.

**Comment by GreatOrator** [comment]
it's an unfortunate side effect of party play with the map.  I have tried to fix it for multiple quests but there are still bugs.  I am watching how mods progress with 1.16 as I am planning on updating the map and pack to that version once everything is updated.
