### ISSUE TITLE
Tents in Front Porch are empty

### ISSUE THREAD

**Issue by samche2000** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#108]
## Description

We are 3 players: Mandrin (op), Lilhyum and Abarurnas. We play on gamemode 2 in the dimension of Middle-Earth map only.

Tents are empty in Front Porch (see screenshots in zip attached).

In GreatOrator let's play, there are some things like bed or chest.

At 24'20 : https://www.youtube.com/watch?v=rqeVBU0sMjI&list=PLLzye8liX-
[20200920124200.zip](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/5251503/20200920124200.zip)
yWDAx2lE_usqxEbTs7BfSfq&index=21&ab_channel=GreatOrator

## Base information
* Minecraft version : 1.12.2
* Minecraft Forge version : 1.12.2-2847
* TolkienCraft III version : 2.0.53

## Server Environment
CPU : Intel Xeon E5 2Vc
RAM : 8Go DDR
HD  : 35 Go SSD
https://www.ouiheberg.com/hebergement-minecraft (Lapis offer)
3 players simultaneous max

### Mandrin (logs from this client)
cf client_dxdiag.txt attached with this issue

### Abarurnas and Lilhyum

Default config from twitch

## Crash report
```
**Logs are attached with this issue**
```

**Comment by GreatOrator** [comment]
They actually are empty...that was intended.
