### ISSUE TITLE
Crash while wearing Mithril armor pieces

### ISSUE THREAD

**Issue by samche2000** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#109]
## Description

We are 3 players: Mandrin (op), Lilhyum and Abarurnas. We play on gamemode 2 in the dimension of Middle-Earth map only.

When wearing a mithril head armor and a mithril leg armor, game crashed and impossible to join server (Internal server error).

A java.lang.NoSuchMethodError is throw on the server console.
[20201010222416.zip](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/5360028/20201010222416.zip)

## Base information
* Minecraft version : 1.12.2
* Minecraft Forge version : 1.12.2-2847
* TolkienCraft III version : 2.0.53

## Server Environment
CPU : Intel Xeon E5 2Vc
RAM : 8Go DDR
HD  : 35 Go SSD
https://www.ouiheberg.com/hebergement-minecraft (Lapis offer)
3 players simultaneous max

### Mandrin (logs from this client)
cf client_dxdiag.txt attached with this issue

### Abarurnas and Lilhyum

Default config from twitch

## Crash report
```
**Logs are attached with this issue**
```

**Comment by samche2000** [comment]
Same with Morgul armor pieces

**Comment by GreatOrator** [comment]
Should be fixed with commit d934ad7 from tolkien mobs
