### ISSUE TITLE
aragron isn't showing up

### ISSUE THREAD

**Issue by doomslayer234** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#111]
## Base information aragon the npc isn't showing up

* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
In creative mode, get the customNPCs wand that looks like a hoe, right click in the air with it and click the reset option.  most likely he is simply not being rendered or fell below ground ( a bug I have seen often).  should fix that.
