### ISSUE TITLE
Chunks missing with the map on serverpack

### ISSUE THREAD

**Issue by danielecaruana** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#117]
First of all, great mod and amazing world, it's great and I've enjoyed playing it on singleplayer. I wanted to play it with my partner but that's where the trouble is unfortuantely.

## Description
I downloaded the map through the mediafire link, and it works perfectly on single player. I then copied the world to the serverpack (that I got from curseforge), and it loaded only a few chunks from the map, with the majority of it being unloaded chunks. I am unsure whether I need to copy anything else other than the world folder.

**Comment by GreatOrator** [comment]
There shouldn't be any difference between loading in single or multi.

Sadly, Development on TC2 stopped many years ago and I am no longer actively working on the map or modpack for that version.

**Comment by danielecaruana** [comment]
Hi @GreatOrator . Thank you for your comment.  The comment is for TC3, rather than TC2. I found another user with a similar issue on a forum recently, however they didn't seem to have a solution. 

When it comes to downloading the map, I assume that the only way is to download it from MediaFire since the button doesn't work right?
