### ISSUE TITLE
Known Crashes & Bugs

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#13]
Currently the following bugs are known:

* Crash when using any of the camping mod hot keys
* Recipe Dupe Pam's and Forestry - water
* Translocators pop-off tinkers smeltery basin once any block cools
* Rendering conflict between Pam's and other mods (primarily BiblioCraft and DecoCraft)

Waiting on response from mod devs, will pull mods if no issue resolution

**Comment by Brillik** [comment]
1. Single player starts in creative mode with JEI config - Item Cheating mode - set to true.
2. Talking to Aragon to get the "Where is the horse and rider" quest line to initiate still requires talking to him three or four times.  He also says the first time that I should talk to other people before talking to him again, but doesn't specify who to talk to, or that I should continue to talk to him.
3. Its not a huge issue, but there are two versions of armorstatus showing on the default hud, one is with Ars magica which is easily turned off with /amuicfg, and the other is RPG-Hud.  But if someone wasn't familiar with ars magica, they may not know how to turn it off.
6. The milestone at the Rhovanion player housing is titled Gondor Housing.
7. The milestone at Rivendell isn't named, so when pulling up the milestone gui there's a unknown destination for Rivendell.  It works fine when talking to stable masters and elsewhere.

**Comment by GreatOrator** [comment]
1. Intentional, while I try to remember to set the overall mode to survival, it leaves the JEI confid intact, once the map is out of alpha that won't be an issue.
2. His overall dialog from the start tells you what people to talk to "the scholars" which is the quest line in BQ and you need to complete that
3. Yeah, still tweaking the HUD, waiting on a specific update from RPG HUD to alleviate that.
4. knew there was something I forgot, will fix that today though may not make it in the map update I am currently in a holding pattern with.
5. Will look into that, it may have lost it's name during one of the map fixes

**Comment by Brillik** [comment]
I cant seem to get Allomancy to work at all. I've consumed so much pewter and tin elixers that I can no longer consume any other flavors, rebound keys and tried everything I can think of without any visible effect.  I was able to get the gui to appear in the hud by consuming a Leserium nugget found in a loot bag, but I haven't been able to get anything to work in either of the 4 groups nor for the gui to change to show that it's working as seen in the youtube videos.  While this isn't a major mod or issue by any means, I feel it is still a bug.

**Comment by Brillik** [comment]
The game crashed while looking in the AM2 book at Compendium Obelisk page 4 and 5.  For some reason the game tries to render half of the image in the environment instead of in the book I was holding.  It was very strange seeing half of the image in the book like normal, and the other half as black blocks on the ground in front of me. Shortly after attempting to render this image, the game totally froze and had to be force closed.  Thankfully, it didn't seem to affect the server, just the client.

[Crash log 7-10-17.txt](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/1136283/Crash.log.7-10-17.txt)

**Comment by Brillik** [comment]
It's happened to me a few times now, but recently when Rumcays came over to visit - I tried to pull out my prized horse (renamed Wilbur) to ride off with him, and my horse disappeared when dumped from the golden lasso.  Frequently, I've had this issue where only 1 prized horse can be present in the chunk at a time, and if theres already one present the golden lasso will empty without the entity appearing.

**Comment by Brillik** [comment]
Better Quest bugs:
1. Job Board > Ancient Evil Mob hunt task isn't completing in Better Quests mods, but registers the kill with the customNPC mod.  All the necessary drops, and faction points are awarded but the mobs are still showing 0/1 complete.
2. A Daring Rescue - Cry for Help - Speak to Munce.  Munce is not giving the quest dialogue or acknowledging that he has a quest to give.  Might be a CustomNPC quest issue.

**Comment by Brillik** [comment]
Pam's Harvestcraft (*) Gardens - Purchased by Amos the Master Farmer do not yield any seeds or pam's food, only vanilla vegetables.  This applies to the Soggy Garden, Frost Garden, Arid, Windy, etc., all of them were tested.

**Comment by GreatOrator** [comment]
> Pam's Harvestcraft (*) Gardens - Purchased by Amos the Master Farmer do not yield any seeds or pam's food, only vanilla vegetables. This applies to the Soggy Garden, Frost Garden, Arid, Windy, etc., all of them were tested.

That's actually how they are supposed to work.  You then place the items dropped in a crafting table to get the seeds.

**Comment by Brillik** [comment]
Harvestcraft problems were resolved with the recent patch.

**Comment by Brillik** [comment]
v 0.12.2 - Better quest bugs previously mentioned are still present.  New quest: Missing husband part 1 works just fine, Part 2: Betan's Rescue step 3/3 NPC quest task - Betan won't initiate rescue scene where he follows player.  The first two location tasks complete just fine, but the third does not.

**Comment by Brillik** [comment]
Quest item missing: Chapter 4 - The path opens II / Dwarven Craftsman - Elrond takes the scroll but does not give a translated scroll in return. I found Lord Dain and did not have a scroll to give him and Elrond won't give me one.

**Comment by timkrieger** [comment]
Probably already known but tossing out here in case someone is looking for the solution to this.
downloaded new 13.1 server from curse, server crashes at startup.  Workaround by downgradeing Chisel to :  Chisel - MC1.10.2-0.0.13.30

**Comment by GreatOrator** [comment]
most of the bugs reported here have since been fixed.  Closing this down until something new comes up.
