### ISSUE TITLE
Mod Interaction - Tinker's Construct w/ Translocators

### ISSUE THREAD

**Issue by snowfiend** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#14]
Using liquid translocators on TiCon smeltery drain into a casting basin causes the translocators to break when molten iron hardens into iron block. Not sure if bug or feature.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2239
* TolkienCraft II version: 0.8.1

## Crash report
N/A

**Comment by GreatOrator** [comment]
Will report this to covers, looks like it is the block update that happens changes the block in such a way that it is popping off as if the block disappeared underneath
