### ISSUE TITLE
"Server Download" button redirects to wrong link

### ISSUE THREAD

**Issue by tomascsantos** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#20]
## Base information
* Minecraft version: 10.0.2
* Minecraft Forge version: 
* TolkienCraft II version: v0.9.2

not a crash report, just a note that the download server button redirects to the old Tolkien craft II GitHub  page

**Comment by GreatOrator** [comment]
Thank you, will be fixed in the next update :D
