### ISSUE TITLE
[QUEST] Wisdom of Lord Glorfindel I #119

### ISSUE THREAD

**Issue by snowfiend** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#33]
## Description
Task 2/2 will not trigger. NPC (Glorfindel) dialog does not engage.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:12.18.3.2281
* TolkienCraft II version:0.11.6

## Crash report
```
N/A
```

**Comment by GreatOrator** [comment]
that was the reason for the map update today, well that and a few other bugs...but yeah
