### ISSUE TITLE
Mob Spawning....

### ISSUE THREAD

**Issue by Teraphina** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#34]
So testing in single player we have found a minor issue.

By default (until mob spawns cant be more easily controlled) doMobSpawning is set to false. This posses a problem in single player as mob spawners are supposed to work and hunger is supposed to go down, and this setting sets the game mode to peaceful. to get around this until this can be fixed you need to lock the game mode in the options menu to Normal, then set /gamerule doMobSpawning false.

This will let mob spawners still work and hunger go down as intended. This will eventually be changed in the config to be automatic but for now those steps will set the mode to the intended outcome.

Again those steps are as followed:

Set game mode in the option menu to "Normal" and press the Lock button,
Click "yes" to agree that you will not be able to change this option,
Then in game bring up chat and type /gamerule doMobSpawning false

Thank You
Teraphina

**Comment by GreatOrator** [comment]
Will check this on my end, though saw your comments about still acting like peaceful as far as player stamina and health which still creates a potential issue.  Definitely have to rethink this mechanic as it is not working as I wanted in single player sadly.

**Comment by GreatOrator** [comment]
Decided to re-enable normal mob spawning since I found a mag torch replacement so this should no longer be a problem.
