### ISSUE TITLE
Map Download progress bar does not display correctly

### ISSUE THREAD

**Issue by Michael-McKinley** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#36]
## Description
Map Download progress bar does not display correctly and does not report total map size

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version: 0.11.6

Map is still downloading, when it past 1/4 GB I started to wonder how big it really was. I am not surprised by the size due tot he amount of content you are creating, however.  

The screen shot shows what I am seeing on download of the Middle Earth map. the first number I believe is the actual number of bytes (based on a 1024:1 ratio) and the more readable shortened version. I also figure you had planned to have the actual size where the third number (0) is.
![map_load](https://user-images.githubusercontent.com/5976433/27006469-68aca6f6-4de9-11e7-9f87-d298f65c3dfb.PNG)

***Update: At 2GB I was about to abort the download, and decided to see if I could find the download location to see if I could find the size.  I did find it, so if anyone else is reading this it is a 2.5 GB download.  Be patient, from past experiences, It will be worth it.

**Comment by GreatOrator** [comment]
lol, I will see if I can get it fixed, but yes, map is just over 2.5 GB

**Comment by GreatOrator** [comment]
This should be fixed after the last update.  If you still have issues, please make sure to note the error log.

**Comment by b51015** [comment]
Noop, still a problem in TolkienCraft II 2.9.5 
I would've interrupted it if I didn't read this (2,5GB)
Are there any files I can send to help?

**Comment by GreatOrator** [comment]
This was closed almost a year ago.

And no, the issue was fixed in 1.12 as I am no longer updating the 1.10 version of this pack since I am working to port it to 1.12, the download is large, just be patient.
