### ISSUE TITLE
Golden Hall of Edoras is broken.

### ISSUE THREAD

**Issue by SOL3675** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#37]
## Description
I went to Edoras and got something wrong XD.
Half of the Edoras has no structures.

![2017-06-11_15 14 02](https://user-images.githubusercontent.com/16431933/27008853-0c5060c0-4eb9-11e7-8016-047be429fbd8.png)

**Comment by GreatOrator** [comment]
Yikes!  Will go there later today and see what happened.  I think I know, but will have to replace from a backup.

**Comment by GreatOrator** [comment]
Easy enough to fix if it is, why I keep so many backups...

**Comment by SOL3675** [comment]
If you fixed it, could you tell me these exact region files that has Edoras?
I mean kinda "r.x.y.mca" file, so I can replace the region data to world I have already started to play.
Anyway, thanks for your support.

**Comment by GreatOrator** [comment]
I just fixed it today actually, looks like when I did some work in worldpainter it wiped out a section of edoras and dunharrow so next map update I will include that plus a number of other small fixes that have been reported.  Don;t really have a way to just replace a few regions unfortunately.

**Comment by SOL3675** [comment]
Okay, I understood. Thanks!
