### ISSUE TITLE
'Click the waypoint in chat' Quest

### ISSUE THREAD

**Issue by edevonport** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#39]
The 'Click the waypoint in chat' quest is not possible as nothing is coming up in chat? Not sure what is meant to trigger it but I have completed 'Chapter Start 1' and 'Welcome to Middle-Earth'

Also having the issue where Darage is Aggressive but have used commands to increase my faction points.
At spawn I spawn on top of the building instead of in and am in creative mode. Which I changed gamemode to 0.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.22.81
* TolkienCraft II version: 0.11.6
## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Open the chat window, there will be a journeymap link in there to click, just like it says :D

**Comment by edevonport** [comment]
There is nothing to click on I just reinstalled and started again but same thing, here is a screen shot.
![screenshot](https://user-images.githubusercontent.com/29373208/27048532-29c549a4-4fa4-11e7-9347-ef3560a11cb7.png)

**Comment by GreatOrator** [comment]
is this ssp or smp?  I can go check the quest book again, but it worked when I tested it

**Comment by edevonport** [comment]
It's ssp, I did see the messages in chat before I updated In a world without the custom maps. But nothing since the map install and update. Is a quest supposed to trigger the link in chat? Maybe I've done something wrong there?

**Comment by GreatOrator** [comment]
The quest from BQ is supposed to place it there actually.

**Comment by edevonport** [comment]
Thanks for the replies, cant seem to get it to work for me. I'll just try again after the next update. Thanks

**Comment by GreatOrator** [comment]
So unless it's missing from the release, the quest has the proper info and when triggered puts it in chat, so going to call this done and when the next release comes out try again.
