### ISSUE TITLE
Cannot get Cave completion Token.

### ISSUE THREAD

**Issue by SOL3675** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#40]
## Description
I reached custom npcs' quest "Hiding in the Dark", and defeated these three trolls of the caves.
I also hold Glorfindel's Beryl and triggered command block events.
I checked the NPC drops, treasure chests and those command blocks. Nothing give me the Token.
Is this a missing features or I missed something?
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:
* TolkienCraft III version: 0.11.6

## Crash report
```
N/A
```

**Comment by GreatOrator** [comment]
I will take a look, the trolls themselves drop the token.  make sure your inventory has room however, just in case.

**Comment by SOL3675** [comment]
I used custom npcs tools to check those drops.
They have no tokens...

**Comment by GreatOrator** [comment]
So just looked, the tokens come from the BQ quests themselves

**Comment by SOL3675** [comment]
Ah, just checking with edit mode, I found it. But can't complete task 2 of BQ quest "Wisdom of Lord Glofindel II".
Score Beryl still 1 for me. I didn't reach the Hiding the Dark quests of BQ side...

**Comment by GreatOrator** [comment]
Yeah there was an "unfortunate" replacement of a crucial command block when I placed the signs in the road, will be fixed in the next update.

**Comment by SOL3675** [comment]
Okay, exact problem is there. Thank you for your support.
I'll add the score with command if I play before the next update.
