### ISSUE TITLE
Glorfindel I bug, cannot talk at waterfall

### ISSUE THREAD

**Issue by Bruno3434** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#43]
## Base information
* Minecraft version: 0.11.8 beta
* Minecraft Forge version: 12.18.3.2281 1.10.2 (mooded)
* TolkienCraft II version:
Latest twitch version.

Hello, i got an issue / bug, in the main line of Tolkiencraft 3 0.11.8 beta, at Glorfindel I, task 2, i cannot talk to glorfindel in waterfall. look to be bug. he say nothing

Do you know how to correct this bug ? (i can edit the quest, to remove the second task, but he doesn't give me the beryl i need for the next quest, btw, nice work

if you find the solution please write to me at nono.34@laposte.net , best regards

**Comment by GreatOrator** [comment]
do you have command blocks enabled (if on a server) and are you using the most recent version of the map?

**Comment by Bruno3434** [comment]
It's not a server, but local host, with LAN. yes, i can make /gamemode 1, or any command. and yes, the most recent version of the map, downloaded yesterday.

**Comment by Bruno3434** [comment]
how to know if commands block are enable?

By the way, outside, there is no monster poping, even at night. maybe some commands are disable

**Comment by GreatOrator** [comment]
Monsters not spawning is on purpose, future plans to have custom mobs spawning

**Comment by GreatOrator** [comment]
So not sure what the bug is, unless you are only following the BQ book.  While it is there it is meant to be your journal, a guide.  Completing quests there does not complete them with CustomNPC's so make sure you are talking to the NPC's
