### ISSUE TITLE
Mass Storage Options

### ISSUE THREAD

**Issue by Brillik** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#44]
## Base information
* Minecraft version:1.10.2
* Tolkiencraft version: III

## Mass Storage Options

1. Refined Storage: [https://refinedstorage.raoulvdberge.com/]
The new AE2 equivalent

2. EZStorage: [https://minecraft.curseforge.com/projects/ezstorage-2]  A pretty simple system that doesn't require energy or tech to run.  

3. Ender IO: [http://enderio.com/] Though possibly too much tech for this pack, has a inventory system now that works fairly well for "mass storage".  But right now I'm having struggles with double the amount of items appearing in the inventory.  The correct amount pull out, but the display is wrong...

4. Colossal Chests: [https://minecraft.curseforge.com/projects/colossal-chests] Listed here as a bit of a joke, the 16x16x16 chest does hold an incredible amount of items.

5. Ender Rift [https://minecraft.curseforge.com/projects/ender-rift] I personally have never used it, but it sounds a lot like something Brandon would make and use with his draconic evolution machines.  It does sound buggy, but might be something worth testing.

**Comment by GreatOrator** [comment]
I'll add EZstorage to my list to watch and we'll see.  It looks the most low-tech of the bunch.

**Comment by GreatOrator** [comment]
With EZ Storage added now I am closing this issue.
