### ISSUE TITLE
Accidentally made backpack private

### ISSUE THREAD

**Issue by SternyBeatbox** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#50]
Hi,

Love the modpack!

I was exploring the settings expandable backpack we start with and made it private.

The owner is now set as GreatOrator and the backpack can't be accessed.

You are likely aware of this, but I thought I'd tell just in case.

**Comment by GreatOrator** [comment]
Well, you should be able to unlock when in creative, I also have a request in to the mod devl to change how that feature works.

**Comment by GreatOrator** [comment]
I figured out a way to give players the backpack without being assigned to a player initially so this should now be resolved.
