### ISSUE TITLE
Server did not start due to missing library "asm"

### ISSUE THREAD

**Issue by CrazyPhysicist** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#52]
## Description
after pulling the server subdir the server does not start with an error indicating  that the asm library is missing.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* TolkienCraft III version: Update v0.13.1-beta

##FIX
reinstall forge => download and run
java -jar forge-1.10.2-12.18.3.2316-installer.jar -installServer

Then startup is no problem but i got two complaints
  Unidentified block: extrautils2:synergy, id 1762
  Unidentified item: extrautils2:synergy, id 6367
 Then it works ;)

Thanks for the work - its great!

**Comment by GreatOrator** [comment]
hmmm, may have been missing a library..i'll look into it, thank you :D
