### ISSUE TITLE
Quest #120 Can't find the scout

### ISSUE THREAD

**Issue by BlackKronos** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#54]
Can't find the scout

## Base information
* 1.10.2:
* Minecraft Forge 12.18.3.2316:
* TolkienCraft III version: 0.13.1

## Issue
```
I can't find the scout, I followed ellendan exact description but can't seem to find the scout. I even checked the surroundings with the CustomNpc Wand. You need the scout to talk to Barachen. I did every other quest, but can't seem to find the scout. Please Help
```

**Comment by GreatOrator** [comment]
Yeah, there is a missing location block, the small camp for the guy is there but the block that completes the quest went missing.  I am trying to get an update out to fix it.  As a stop-gap you can pull a CNPC location block (black block with a green circle) and place it near the NPC to complete the quest before the update.

**Comment by BlackKronos** [comment]
Thank you
Loving the pack btw

**Comment by BlackKronos** [comment]
I'm not that familair with CustomNPC. So may I ask which NPC and Do I have to give the location block a specific name ? Thanks 👍

**Comment by GreatOrator** [comment]
Barachan I think was his name, he's near the river.  The coordinates are in the quest book for his location BTW.

Glad you're enjoying the pack :D
