### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by YBRxHaVoK** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#55]
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by YBRxHaVoK** [comment]
heres the crash log
[crash-2017-10-13_21.26.58-server.txt](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/1384403/crash-2017-10-13_21.26.58-server.txt)

**Comment by GreatOrator** [comment]
Alright, yeah that is a crash that was mentioned in the comments of the pack, change the version of chisel in the server package to match the version in the client.  just delete the one on the server and copy over the one from the client.
