### ISSUE TITLE
game crashes when attempting to install map

### ISSUE THREAD

**Issue by rjwolfe3** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#58]
[crash-2017-11-16_14.52.29-client.txt](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/1480242/crash-2017-11-16_14.52.29-client.txt)

**Comment by GreatOrator** [comment]
http://repository.a2g.gs/modpacks/tolkiencraft/3/MiddleEarth-DefaultTC3.zip

that's the download link.  Will let brandon know as it looks like the compression handler is broken.

**Comment by rjwolfe3** [comment]
Is there something I can do or do I need to just be patient and wait for a fix?

**Comment by GreatOrator** [comment]
Maybe, maybe not, why I have to speak to brandon.  That link will let you download the map to add it to your saves folder.

**Comment by GreatOrator** [comment]
We have been testing and can no longer replicte the error.  If you still can, please try opening up the zip file that is downloaded (it will be found in the saves folder) to see if it will open up.  If so, then provide a crash report/error log.  If not, just let me know that's the case and we'll go from there.
