### ISSUE TITLE
Can not install dev version. Extended character sequence in customnpcs filename.

### ISSUE THREAD

**Issue by heatskr** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#59]
## Description
Can not install the development version with **Twitch** and **Mac OS X**.
Disk is not full. There is a **character sequence** in file basename.
**overrides/customnpcs/clones/1/Gl?in.json**
Please **rename** the assets.

## Base information
* Twitch Modpack Installer
* Mac OS X High Sierra
* Case-sensitive filesystem
* Java 1.8-151

## Crash report
![lotr3](https://user-images.githubusercontent.com/348713/34315565-2b50f35a-e760-11e7-86aa-e5316a141259.png)

**Comment by GreatOrator** [comment]
It is a known issue with a couple of mods, it is the way apple handles file paths has has been reported to the mods affected.  Just no fix has been implemented as of yet.

**Comment by heatskr** [comment]
@GreatOrator  In this case rename the customnpcs character names to english only. It will help with internationalization and portability. For example Gl?in.json to Gloin.json.

**Comment by GreatOrator** [comment]
That is a factor of the file name.  there is a special character in the name of the file that keeps getting messed up.

**Comment by captainrbaker** [comment]
Hi GreatOrator. 

I am having this problem when I try to download pack from Twitch. I am using a Mac if that matters. It will load from version 0.9 and down but nothing above this version will install. I have tried reinstalling a fresh install of the pack and twitch but no luck. Sorry if this has been addressed elsewhere. Do you have a current workaround or should I wait for a new version.? 

Regards

**Comment by GreatOrator** [comment]
That is because the newest version is considered beta, you have to manually go and look at versions in the twitch launcher and tell it to update to the newest version

**Comment by captainrbaker** [comment]
Yeah I tried that . I keep getting the same error as above . Any version above 0.9 won’t install. I installed the 9.0 version and then tried to update from twitch accordingly with no luck. Keep getting the same custom noc error. 

I may have done something wrong but I tried for about 3 hours and many different ways. And no luck. It won’t install or update to the latest version. 

Thanks for your help.

**Comment by GreatOrator** [comment]
Unfortunately at this point you may need to contact curse for help as it is an issue with the launcher.  I tried several different ways and was able to install each time.

**Comment by captainrbaker** [comment]
Ok I’ll try curse. 

Such a shame as I have been away from Minecraft for a while and just getting back into it. Your packs are always my first call. 

Just for the sake of giving you as much info as possible. I downloaded the pack directly from curse forge and tried to import that way and still no luck. Twitch app won’t even begin to install it. 

And when I go into the custom npc folder it does have a file with a funny character in the name.  One of the ones that starts with G.Sorry can’t remember the name exactly. But that is what is causing the error for me. It stops loading as soon as it gets to that stage. The versions before 0.10 don’t have that name and install ok. 

I hope it is something twitch can fix as I am not quite ready to give up yet. Is there another way I can get the pack? Or any other ideas I could try? 

I have had nothing but trouble with twitch on Mac. 

Anyway thanks for your help. And good job on the pack. I’ll have to stick with watching your let’s plays for now.

**Comment by captainrbaker** [comment]
Hi GreatOrater.

I ended up going the multiMC route. Worked fine. RIP twitch app. 

Regards

**Comment by GreatOrator** [comment]
Yeah, that is why I use MultiMC myself, only reason for using twitch is for distribution channels.  But, that is why I make the updates available here on github as well.

Will take a look at the special character.  I could have sworn I had changed/removed all of those.
