### ISSUE TITLE
Twitch app downloads wrong version.

### ISSUE THREAD

**Issue by DuelRevolvers** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#60]
## Description
When I download the modpack off of the twitch app, it says it's 13.1 but when I open it, it says 12.2 in the corner in the main menu screen.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* TolkienCraft III version: 12.2/13.1

**Comment by DuelRevolvers** [comment]
The server is downloading the wrong version, as well.  It's wanting an older version of forge.

**Comment by GreatOrator** [comment]
i'll double check the server package, but the main menu...yeah I forgot to update that often :P

**Comment by DuelRevolvers** [comment]
Ah ok, thanks!
