### ISSUE TITLE
Talked to Aragorn BEFORE getting his quest horse and rider complete 

### ISSUE THREAD

**Issue by rexmasters** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#61]
I was able to get the actual quest  where i need to talk to him, and now, no matter what I do, I can't mark horse and rider as complete, even though the first part is complete, and I talked to Aragorn already.

**Comment by GreatOrator** [comment]
Try talking to the guy at the camp again, usually where the breakdown is, though issues like this I can answer much faster in my discord.
