### ISSUE TITLE
Can not install on Twitch

### ISSUE THREAD

**Issue by heatskr** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#64]
### Problem
Custom NPCs file names are using unsecured characters that only work in specific environments.

### Solution
Rename files to secured characters for compatibility, portability and internationalization.

"Glóin.json" will become "Gloin.json" with secured [a-z, A-Z, 0-9] only characters.

### Example

Error to install on Twitch with modern system and Brazilian Portuguese environment.

![lotr3](https://user-images.githubusercontent.com/348713/36343037-6f38db80-13e5-11e8-8cd4-c85ebf2bb44f.png)

**Comment by GreatOrator** [comment]
I will look into this for foreign PC's though the characters are in standard ascii format.

**Comment by heatskr** [comment]
@GreatOrator Please rename Gloin without "acute". Extended ascii character number 162 must be standard ascii number 111. http://www.asciitable.com

**Comment by GreatOrator** [comment]
Finally decided since this seems to be the only file name with an issue (even my ftp client doesn't like it) I will have it renamed in an upcoming update.
