### ISSUE TITLE
Server not compatible

### ISSUE THREAD

**Issue by LSperwer** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#65]
Hello,

I installed the latest beta server pack (v0.13.35), and installed the latest version of the modpack on twitch (beta) but when i try to join the server there are missing some mods.

**Comment by GreatOrator** [comment]
Actually yeah, forgot to update the server package.  You can either downgrade the client pack for chiselsnbits to .16 or upgrade the server to .17 to fix the error.
