### ISSUE TITLE
0.13.35 server version not working.

### ISSUE THREAD

**Issue by DuelRevolvers** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#66]
## Description
I think the provided 0.13.35 server version is incorrect. The list of Mods in the mods folder is old. Is there a fix I do to get it working? I get the incompatible fml modded server error under the server.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:12.18.3.2511
* TolkienCraft III version:0.13.35

**Comment by GreatOrator** [comment]
Already covered in https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/issues/65
