### ISSUE TITLE
map download not working

### ISSUE THREAD

**Issue by tabular09** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#71]
## Description
every time I try to download the base map to play the download stops about 50% through and does not restart. do not know if this is my internet or not but usually when mine stops it picks up again in a few minutes.
## Base information
* Minecraft version:1.10.2
* Minecraft Forge version: do not know where to find.
* TolkienCraft II version:0.13.52

## Crash report
```no crash
CRASH REPORT HERE
```

**Comment by tabular09** [comment]
game does not chrash

**Comment by GreatOrator** [comment]
We have been looking in to this but can not replicate it, even multiple attemps on my pc download fine.  If you can provide any information about any errors in logs, type of computer, etc it would help.

**Comment by tabular09** [comment]
[2018-07-11-1.log](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/2186995/20
[fml-client-latest.log](https://github.com/GreatOrator/TolkienCraft-3-Return-to-Middle-earth/files/2186997/fml-client-latest.log)
18-07-11-1.log)
here are a couple of logs I have found one might be about the download from the right time

**Comment by GreatOrator** [comment]
Sadly it contained nothing about the download (though plus side it did highlight a different error with one off the sounds I added to customNPC's which I was able to fix).

You can use the open link in a browser option to download, though you will have to add the map manually to your saves directory unfortunately.

**Comment by tabular09** [comment]
thank you for the suggestions ill keep trying and see what comes from. ill also try a different browser than chrome

**Comment by tabular09** [comment]
worked in Microsoft edge but not on my chrome probably something wrong on my chrome install

**Comment by GreatOrator** [comment]
interesting, especially since chrome is my default browser.  Glad you could get it downloaded though.
