### ISSUE TITLE
I cannot complete first quest, when i talk to aragorn it doesnt complete the quest

### ISSUE THREAD

**Issue by felixdoktor** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#73]
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Make sure you are reading what he says.  You have to go visit all of the "Scholars of Middle-earth" to continue on the quests

**Comment by felixdoktor** [comment]
Yeah i know but the quest, speak to aragorn. When i speak to him it dosnt
makr it as done

**Comment by GreatOrator** [comment]
Have you completed all of the quests in the scholars line?

**Comment by felixdoktor** [comment]
Ok, thank you, works now
