### ISSUE TITLE
Painting(Job Board) not appeared, Quest Book wasn't in a starter gear

### ISSUE THREAD

**Issue by nickseo7** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#75]
## Description
A major bug and a minor bug
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2511
* TolkienCraft II version: 1.0.1 (btw there's a typo as II, not III)

## Crash report
![2018-09-20_17 16 29](https://user-images.githubusercontent.com/37957120/45917140-0574e780-beac-11e8-86a8-dbba09dd82fc.png)
The painting wasn't loaded(coordinates above), and when I picked up the painting and tried to put it back, crash occurred.
And the starter gear didn't include a quest book.

CRASH REPORT HERE
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 9/20/18 5:08 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at jds.bibliocraft.gui.GuiPainting.func_146979_b(GuiPainting.java:485)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at jds.bibliocraft.gui.GuiPainting.func_146979_b(GuiPainting.java:485)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: jds.bibliocraft.gui.GuiPainting
	Mouse location: Scaled: (238, 142). Absolute: (714, 408)
	Screen size: Scaled: (480, 279). Absolute: (1440, 837). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['nickseo'/374, l='MpServer', x=14693.31, y=50.00, z=12273.58]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (14911,143,5960), Chunk: (at 15,8,8 in 931,372; contains blocks 14896,0,5952 to 14911,255,5967), Region: (29,11; contains chunks 928,352 to 959,383, blocks 14848,0,5632 to 15359,255,6143)
	Level time: 909926027 game time, 169682689 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityOcelot['Ocelot'/4864, l='MpServer', x=14730.50, y=50.00, z=12264.50], EntityOcelot['Ocelot'/4865, l='MpServer', x=14734.50, y=50.00, z=12265.50], EntityOcelot['Ocelot'/4869, l='MpServer', x=14750.20, y=52.00, z=12338.31], EntityOcelot['Ocelot'/4870, l='MpServer', x=14767.50, y=49.00, z=12317.50], EntityOcelot['Ocelot'/4872, l='MpServer', x=14735.78, y=53.00, z=12347.22], EntityOcelot['Ocelot'/4873, l='MpServer', x=14738.78, y=53.00, z=12342.50], EntityOcelot['Ocelot'/4874, l='MpServer', x=14744.90, y=53.00, z=12345.28], EntityHorse['Horse'/4879, l='MpServer', x=14713.76, y=51.00, z=12320.17], EntityOcelot['Ocelot'/4882, l='MpServer', x=14699.75, y=48.00, z=12213.83], EntityOcelot['Ocelot'/4884, l='MpServer', x=14685.68, y=49.00, z=12223.53], EntityPlayerSP['nickseo'/374, l='MpServer', x=14693.31, y=50.00, z=12273.58], EntityCustomNpc['Golraith'/4772, l='MpServer', x=14507.58, y=46.00, z=6298.84], EntityHorse['Horse'/4800, l='MpServer', x=14706.80, y=51.00, z=12316.80], EntityHorse['Horse'/4801, l='MpServer', x=14706.80, y=51.00, z=12313.80], EntityHorse['Horse'/4802, l='MpServer', x=14707.02, y=51.00, z=12311.61], EntityHorse['Horse'/4803, l='MpServer', x=14713.66, y=51.00, z=12313.39], EntityCustomNpc['Golraith'/4804, l='MpServer', x=14709.30, y=51.00, z=12312.93], EntityCustomNpc['Ambience'/4805, l='MpServer', x=14719.50, y=49.00, z=12306.50], EntityOcelot['Ocelot'/4857, l='MpServer', x=14749.26, y=49.00, z=12274.54], EntityOcelot['Ocelot'/4858, l='MpServer', x=14718.50, y=50.00, z=12265.50], EntityOcelot['Ocelot'/4859, l='MpServer', x=14721.97, y=50.00, z=12253.76], EntityOcelot['Ocelot'/4860, l='MpServer', x=14726.50, y=50.00, z=12253.50], EntityOcelot['Ocelot'/4861, l='MpServer', x=14721.82, y=50.00, z=12267.90], EntityOcelot['Ocelot'/4862, l='MpServer', x=14720.82, y=50.00, z=12260.65], EntityOcelot['Ocelot'/4863, l='MpServer', x=14721.13, y=50.00, z=12261.16]]
	Retry entities: 1 total; [EntityCustomNpc['Golraith'/4772, l='MpServer', x=14507.58, y=46.00, z=6298.84]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1603129152 bytes (1528 MB) / 4466409472 bytes (4259 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	allomancy{2.2.1} [Allomancy] (allomancy-2.2.1.jar) 
	UCHIJAAAA	antiqueatlas{4.4.6} [Antique Atlas] (antiqueatlas-1.9.4-4.4.6.jar) 
	UCHIJAAAA	antiqueatlasoverlay{1.2} [Antique Atlas Overlay] (antiqueatlas-1.9.4-4.4.6.jar) 
	UCHIJAAAA	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	atlcraft{1.10.2-Ver1.5} [ATLCraft Candles Mod] (ATLCraftCandlesMod(MC1.10.2-Ver1.5).jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	hud{1.3.8} [Better HUD] (Better HUD by NukeDuck [1.9.4][1.3.8].jar) 
	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAAAA	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHIJAAAA	betterquesting{2.3.234} [Better Questing] (BetterQuesting-2.3.234.jar) 
	UCHIJAAAA	bqt{0.9} [Better Questing Triggerer] (BetterQuestingTriggerer-0.9.jar) 
	UCHIJAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.11-80.jar) 
	UCHIJAAAA	bqt_tolkien{1.0.0} [TolkienCraft Theme [BQ]] (BQ_TolkienTheme-1.0.0.jar) 
	UCHIJAAAA	bqmie{1.0.0} [BQMIE] (BQMIE-1.10.2-1.0.0.1-universal.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.14} [Brandon's Core] (BrandonsCore-1.10.2-2.1.14.137-universal.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.2.0.43} [Chisel] (Chisel-MC1.10.2-0.2.0.43.jar) 
	UCHIJAAAA	chiselsandbits{12.17} [Chisels & Bits] (chiselsandbits-12.17.jar) 
	UCHIJAAAA	compatlayer{0.3.1} [compatlayer] (compatlayer-1.10-0.3.1.jar) 
	UCHIJAAAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAAAA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJAAAA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.7-universal.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.5.2_1.10.2.jar) 
	UCHIJAAAA	props{2.5.2} [Decocraft] (Decocraft-2.5.2_1.10.2.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.6.jar) 
	UCHIJAAAA	forestry{5.2.17.388} [Forestry] (forestry_1.10.2-5.2.17.388.jar) 
	UCHIJAAAA	eleccore{1.7.431} [ElecCore] (ElecCore-1.10.2-1.7.431.jar) 
	UCHIJAAAA	mcjtylib_ng{2.5.3} [McJtyLib] (mcjtylib-1.1x-2.5.3.jar) 
	UCHIJAAAA	deepresonance{1.4.9} [DeepResonance] (deepresonance-1.1x-1.4.9.jar) 
	UCHIJAAAA	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	draconicevolution{2.1.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.8.273-universal.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAAAA	ezstorage{2.3.2} [EZStorage 2] (ezstorage-2.3.2-[1.10.2].jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-anarchy.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAA	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.10.2.jar) 
	UCHIJAAAA	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	jaff{1.5.3_for_1.10.2} [Just a Few Fish] (JustAFewFish-1.5.3_for_1.10.2.jar) 
	UCHIJAAAA	justenoughdimensions{1.5.4} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.5.4.jar) 
	UCHIJAAAA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJAAAA	keywizard{1.10.2-1.5} [Keyboard Wizard] (keywizard-1.10.2-1.5.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.10-1.10.2.jar) 
	UCHIJAAAA	lootbags{2.5.0} [Loot Bags] (LootBags-1.10.2-2.5.0.jar) 
	UCHIJAAAA	MadHelp{2.0.1} [Mad Help] (MadHelp-1.10.2-2.0.1.2-universal.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAA	modularrouters{1.10.2-1.4.2} [Modular Routers] (modular-routers-1.10.2-1.4.2.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCHIJAAAA	bq_npc_integration{CI_MOD_VERSION} [NPC Integration] (NPCIntegration-2.3.22.jar) 
	UCHIJAAAA	oreexcavation{1.2.114} [OreExcavation] (OreExcavation-1.2.114.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	PerfectSpawn{1.4} [Perfect Spawn] (PerfectSpawn-MC1.10.2-1.4.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	petbuddy{1.11 2.3.1.7 backport for 1.10} [Pet Buddy] (petbuddy-1.10.2-2.3.1.9 .jar) 
	UCHIJAAAA	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UCHIJAAAA	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	railcraft{10.3.1} [Railcraft] (Railcraft_1.10.2-10.3.1.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	corerm{1.2e-1.9.4} [RikMuld's Core] (RikMuldsCore_1.2e-1.10.2.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	bq_standard{2.3.131} [Standard Expansion] (StandardExpansion-2.3.131.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	camping{2.3d-1.9.4} [The Camping Mod 2] (TheCampingMod_2.3d-1.9.4.jar) 
	UCHIJAAAA	thut_wearables{1.1.3} [Thut's Wearables] (thut_wearables-1.1.3.jar) 
	UCHIJAAAA	thutcore{3.21.0} [Thut Core] (thutcore-3.21.0.jar) 
	UCHIJAAAA	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tolkientweaks{2.0.4} [Tolkien Tweaks] (TolkienTweaks-1.10.2-2.0.4.24-universal.jar) 
	UCHIJAAAA	torchmaster{1.4.1.34} [TorchMaster] (torchmaster_1.10.2-1.4.1.34.jar) 
	UCHIJAAAA	torchoptimizer{1.10.2-2.0.4} [Torch Optimizer] (torchoptimizer-1.10.2-2.0.4.jar) 
	UCHIJAAAA	TownBuilder{1.0.0-Build8} [Town Builder] (TownBuilder-1.10.2-2.0.0.1-universal.jar) 
	UCHIJAAAA	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.4.1.0.jar) 
	UCHIJAAAA	Woot{1.10.2-1.4.1} [Woot] (woot-1.10.2-1.4.1.jar) 
	Loaded coremods (and transformers): 
CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
llibrary (llibrary-1.7.7-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
  lumien.perfectspawn.asm.PSClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	Launched Version: forge-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by GreatOrator** [comment]
They are there, if you look at the resourcepacks option you should see a resource pack that was made just for that.  I am seeing some cases where minecraft is not using the default options I put in place to make sure it auto loaded.

**Comment by nickseo7** [comment]
I forgot that custom paintings need resource pack, my bad.

**Comment by GreatOrator** [comment]
no worries, would have been more concerned if you said it wasn't there :P
