### ISSUE TITLE
Can't finish tutorial quest line

### ISSUE THREAD

**Issue by mdan227** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#77]
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-12.18.3.2511
* TolkienCraft III version: 1.1.2
* Using Twitch Launcher

## Description
After speaking to all of the people Aragorn asks me to speak to (the recorder, the stablemaster, both real estate agents, and the monk), and making sure to go through all of the dialogue options for each of them, the final task of the final quest still won't pop, and it won't let me speak to Aragorn when I return to Rivendell. 

I had this issue in the first full release version, but I updated to this new version to see if it fixed it, and it still hasn't. Not sure if there's something I'm missing in the quest, or if something just isn't triggering for me. I've tried using edit mode to just mark the quest as complete, but that still doesn't let me talk to anyone, so I'm just left with no quests or anyone to talk to.

**Comment by GreatOrator** [comment]
What do you currently have listed in you customNPC quest log?  I will check my dev version to verify the quest chain.

**Comment by GreatOrator** [comment]
Alright, found the issue, use /noppes quest start (playername) 168

that should give you t he quest you're missing.  I'll try to get out an update though to fix it, not sure when that disappeared...

**Comment by mdan227** [comment]
Thanks for the quick reply. Your fix worked to get me the quest needed to talk to Aragorn. But, when I talk to him, the dialogue is cut short. He greets me, I say something, he responds, and then there's a pause for me to hit the next dialogue prompt, but it never appears. I can only exit the conversation and restart it, but it never goes further than that, so I can't complete the first quest of the first chapter.

**Comment by GreatOrator** [comment]
Does the quest say to speak to aragorn to complete?

**Comment by mdan227** [comment]
Yeah, it's the first quest from chapter 1. The first task is to just find Aragorn (which popped for me) but then the second task is to talk to Aragorn, and I can't complete that because the dialogue just cuts off in the middle of the conversation.

**Comment by bejarrodar** [comment]
did anyone figure out how to fix this I am having the same problem I used the command to start the quest but it wont let me retalk to Aragorn to get the quest to talk to Elrond

Never mind I looked through the files and found that the next quest was id 8

**Comment by GreatOrator** [comment]
Will be looking at this one this afternoon, not the first time I have had an earlier part of a quest chain break for unknown reasons in my packs :P

**Comment by GreatOrator** [comment]
Ok, so the second dialog with aragorn gives you the quest to speak to elrond, there is only the one page, tested and confirmed, the next dialog will be with elrond

**Comment by GreatOrator** [comment]
If the quest lay of the land did not complete and the BQ book is not proceeding, use /noppes quest stop <playername> 168

**Comment by mdan227** [comment]
Quest 168 completed for me, but Aragorn's dialogue still wouldn't complete. As a quick work-around, I used /bq_admin to just complete the BQ quest that required me to speak to Aragorn, and then used /noppes to start the next custom npc quest (8), which lets me go ahead and talk to Elrond, and seems to have allowed me to continue the story without having to finish that conversation with Aragorn. Not exactly fixing the problem, so much as skipping over it, but it allows me to keep playing, and hasn't seemed to break anything else yet. Will update if something else acts wonky.

**Comment by salanga** [comment]
i still have this problem with aragon.
this next bit is from when i wanted to post a bug report and github send me to this post.
i am stuck on the troubles of rivendell quest. i watched your playthrough up to just past this point so far greatorater and when you go to talk to aragon he gives you a second line to talk with him. when i talk to him i can say that it was a long journey but after doing that he gives his reply and never gives me another option to keep talking. if i try anything the text closes and i can try again to talk to him, starting all over and never progressing.

@mdan227 what command did you use to skip the customnpc part of this?

**Comment by GreatOrator** [comment]
I'll take a look, but right now I am porting the whole pack to 1.12 which involves basically re-setting all of the quests so this should no longer be an issue in 1.12.  As for the commands, he mentioned them in his comment
