### ISSUE TITLE
Chest = Stairs

### ISSUE THREAD

**Issue by hellamie** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#79]
## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:12.18.3.2511
* TolkienCraft II version:1.17

## Crash report
```
![2018-10-22_09 44 41](https://user-images.githubusercontent.com/12673700/47283934-9f33cf80-d5e5-11e8-95f2-a2a0b2bff564.png)
https://cdn.discordapp.com/attachments/471894531868983297/503501018101841940/2018-10-21_11.32.29.png  = Tinker Schmelze

No Tinkers. No Chest No Torch. Every Item ist wrong.

```

**Comment by teagan75** [comment]
First of all, if you are playing Tolkiencraft II on Minecraft 1.10 That is your issue. It’s a 1.7.10 pack only

**Comment by teagan75** [comment]
That is not a crash report. Go into your .minecraft folder or instance folder for TC3 and find the crash report folder. Attach the latest report here.

**Comment by GreatOrator** [comment]
Anytime you have items that are incorrect this is related to not having the correct version of the pack with the map.  Closing issue because no proper crash log or examples.
