### ISSUE TITLE
Cannot progress through quests

### ISSUE THREAD

**Issue by Irishbelle** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#80]
When i first started the game, the quest with the beryl would not complete, however I later found after much digging that it was due to the command blocks being disabled, once that was fixed the quest seemed to fix itself, however, since that point I've had nothing but issues trying to progress through the quest. 

From the moment that I had to enter the troll caves it's been a rocky go of it. First the quests would not complete after visiting the 3 caves, I had to run back and forth between the caves multiple times after killing the trolls just to finally get a completion. 

Then came the moment where I had to go back to find a giant with the help of Legolas, however, all he would say is "Hello", never triggering another part of the quest, despite the previous quests being complete. My husband was having the same issue, however once we disbanded the party, when he went to speak with Darage he was able to reset his quest and eventually get Legolas to teleport him to the giant and then complete the quest upon his return. 

I've tried the same thing without the same results. I even tried getting a new quest book and that didn't do anything. I've deleted my saves from the server and anything else that I could find with my id on it on the server, even deleted my world file on my local and copied it fresh from the backup I had from the original file we downloaded. I've repaired the minecraft file as well through twitch and in all honesty nothing is happening. 

I was able to start up again, however, it's stuck back on the trolls again as I am not getting the tokens for  killing the trolls to move forward. I honestly don't know what else to do at this point other than completely trashing the server and starting it over again, however, that would mean destroying our homes as well.. I don't know what else to do though. I hope you can help..

**Comment by GreatOrator** [comment]
Well, the tokens come from the three quests in the book after you kill each troll, the location completion is dependent on you being in the right location to hold up the beryl.  I just recently went through those quest due to an earlier quest bug and as long as you follow the book and the NPC log pretty much at the same time, there should not be those issues.

**Comment by Irishbelle** [comment]
Yeah the first time I went through the quests I didn't have the command blocks enabled, so I shut down the server, restarted after enabling them and the beryl part was complete.  I was then able to proceed until we needed the tokens for killing the giants, which I received and had to run back and forth between Brachen and Elladan a couple of times, eventually it completed. The last one was the knowledge of giants where you have to talk to Legolas and I haven't been able to talk to him. He just keeps saying hello. I tried talking to Darage to reset and nothing reset, I was still having the same issue. My husband was having the same issue as well, but after leaving the party he was able to get it to work. I have not been so lucky.

I even went as far as to delete my world locally, and all the ID files that pertained to myself on the server, which started me back at level 1 again and I had to go through the quests again, however, when I would press "O" to open the quest log, all my quests are there still, but I was able to talk to everyone from the beginning, however, now I am stuck with killing the 3 giants yet and they are not giving me any drops for the coins so that I can move on and hopefully be able to talk to Legolas again. I even deleted all my inventory, asked for a new quest book, asked to reset my quest progression, etc.. nothing is working. I would like to continue playing this but it seems like now the only way is to delete the server, completely uninstall the game (and not just repair it) and start from scratch which.. is less appealing to be honest because there seems to be no guarantee that it will work

**Comment by checco-01** [comment]
hi ,i have a problem after the event "ambush" i can't progress after becouse im not allowed to talk with layles what should i do to continue?

**Comment by GreatOrator** [comment]
Have not forgotten this, just been extremely busy with the holidays.  It is on my bucket list to check still though.

**Comment by GreatOrator** [comment]
With the release of the 1.12 version of the pack, and multiple reports that this is no longer and issue, going to call it closed.  if it crops up again, please submit a new report.
