### ISSUE TITLE
layles

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#81]
## Description
hi ,i have a problem after the event "ambush" i can't progress after becouse im not allowed to talk with layles what should i do to continue?
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft III version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
I have noticed that being buggy for some reason, if you go in to edit mode in bq /bq_admin edit

in that category a hidden quest will show up, force completee it should restart progression.

**Comment by checco-01** [comment]
it still doesnt work i have compleated the quest "ambush" but i cant talk with layles as you have done in your gameplay.

**Comment by GreatOrator** [comment]
I will check in my dev instance and see what I can do for you.

**Comment by checco-01** [comment]
thanks for the help you are giving to me

**Comment by GreatOrator** [comment]
Sorry about not having got back to you yet, the holidays have made it very tough to get any time.  Still on my list to review though so have not forgotten.

**Comment by checco-01** [comment]
have you find any solution?

**Comment by GreatOrator** [comment]
At this stage I am basically redoing all of the quests from start to finish since I am also porting to 1.12 of minecraft.  Hopefully this rework will fix this issue and several others.
