### ISSUE TITLE
Layles

### ISSUE THREAD

**Issue by Zechr29** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#84]
## Description
After defeating the goblins/orcs in the dungeon i cannot talk to Layles. I have tried reseting/completing the quest using /bq-admin but it still doesn't work I CANNOT TALK TO LAYLES, i saw the other issue called layles but it doesnt appear to have a clear fix posted on it. 
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:
* TolkienCraft III version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
there should be a quest in BQ that triggers the second part of the quest once you get the proper kill count in the npc quest.   In BQ it is a hidden quest which I normally placed on the right hand side in the chapter so you may need to be in edit mode to activate it.

**Comment by GreatOrator** [comment]
This issue should be fixed in the newest release for tolkiencraft for minecraft 1.12.  if you have issues with this again in 1.12 (v2.0.0+) please submit  a new issue report.
