### ISSUE TITLE
Matuna's cave not working

### ISSUE THREAD

**Issue by Fruittuitella** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#85]
After i kill Matuna at his cave, he drops everything including his key as he's supposed to, but the mission doesn't complete, also, when i watch a walkthrough, after they kill him, there pops up a mini npc or something? He doesn't show up at my game though. What do i need to do to finish my quest?

**Comment by Fruittuitella** [comment]
Never Mind, i reloaded the quest in The House of Elrond and completed it.

**Comment by Fruittuitella** [comment]
there was no little elf though

**Comment by GreatOrator** [comment]
The "little elf" is the my buddy mod :D  I makes a mini you when you press f7 (at least that's the hot key I have it set to) and if you give it weapons and stuff it will fight with you.

**Comment by Fruittuitella** [comment]
ah okay, nice tip! Thanks!
