### ISSUE TITLE
Crash with Glorfindel's Beryl

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#88]
## Description
Crash to desktop while holding Glorfindel's Beryl. When I reloaded I still had it in hand and didn't crash. I think I tried to use it and tested that and sure enough I crashed.

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: forge-14.23.5.2838
* TolkienCraft III version:  1.12.2-2.0.0

## Crash report
```
https://pastebin.com/MHqbCkGT
```

**Comment by GreatOrator** [comment]
Ooooh, guess I never thought about people trying to actually use the item.  Will take a look and see about some error checking.

**Comment by GreatOrator** [comment]
Found and fixed it.  Once I complete my new mob it'll be in the update.
