### ISSUE TITLE
LAN crash

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#89]
## Description
game crashes to desktop when trying to open LAN

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: forge-14.23.5.2838
* TolkienCraft III version: Version: 1.12.2-2.0.0

## Crash report
```
https://pastebin.com/yqrFQsGj
```

**Comment by GreatOrator** [comment]
change config option in madhelp

B:disableLaneCheatMode=false

Will update this in my dev.  Was a hold over from TC2 when I did not want players to be able to go in to creative by any means.
