### ISSUE TITLE
Real estate agent is non existent  

### ISSUE THREAD

**Issue by mitchngwen** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#91]
I just started play tolkiencraft 3 1.12.2, I have a major issue that is keeping me from progressing, I can not find the real estate agent, there are no coordinates for his location, just a sentence that says he is near Rivendell,  I have roamed all over rivendell and on the outskirts of rivendell and I can not find him. Could I get the exact coordinates please?

**Comment by GreatOrator** [comment]
Follow the paths and signs out of rivendell.  If you are using the latest pack version, coordinates for journeymap were displayed in chat.

**Comment by mitchngwen** [comment]
I am using the latest version and I did not see any signs, I also never saw coordinates in chat. The other 2 quest had the coordinates but this quest does not, it's weird,

**Comment by teagan75** [comment]
there are three player housing areas. The Rivendell one is near the High Pass. If you took the road straight out and went past the stables, you will come to a sign that tells you to cross the river. It's a long trek. I had a hard time too :D

**Comment by mitchngwen** [comment]
Awesome! Thank you.
