### ISSUE TITLE
Server freezing 

### ISSUE THREAD

**Issue by mitchngwen** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#92]
Playing the latest Tolkiencraft. 1.12.2 Now that I have found player housing the server just freezes up and then crashes because a single tick took too long. Is this a common issue? Is there a fix? Do you need a log?

**Comment by GreatOrator** [comment]
Yes, I will need a log to try to figure out what is happening as well as which verion of the map you are using and version (specifically) of the pack.
