### ISSUE TITLE
reduction of spawing npc

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#93]
## Description
my pc is quite old and near large cities like rivandale and bree it freezes a lot,witch file i have to modify to reduce the spawing of npc's?
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
As I mentioned in the previous report.  The tolkienmobs config is where you can adjust mob spawning.  This only impacts my mobs.  The alternative is to just use /gamerule domobspawning false and /gamerule domobspawn false in game.
