### ISSUE TITLE
"on an adventure" quest, bugs and temporary fixes

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#95]
## Description
the quest asks you to talk with Ermengard after talking with Adalbert, but she only says the base dialog (hello player)  so the quest can't procede,i have cheked and she has the "missing hobit V"as a dialogue but it doesn't start.
## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version:) 14.23.5.2847
* TolkienCraft II version:1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by checco-01** [comment]
sort of fixed myself, first you need to edit the quest 187 tolkiencraft/saves/word/customnpcs/quest/on an adventure in the category "completenpc" you must add  Clayhanger inside the 
quotation marks,but then you also must add the "missing hobit VI" dialog to a random character,only then the quest missing hobit II will be activeted,then you procede as you normaly would.

**Comment by checco-01** [comment]
after talking with petunia you should talk with tom bombadil he asks you to find a waterfall,after that the dialogs "making a new friend" 4 to 6 should be aviable,but the dialogs dont start,an easy fix is to temporary  replace the dialog "making a new friend 1" with "making a new friend 3"

**Comment by GreatOrator** [comment]
i will re-test the quest chain to make sure.  since the map update is out already, if I do find a fix or issue it won;t be released until the first week of december

**Comment by GreatOrator** [comment]
Quest line has been fixed.  Most of it should be corrected when I release the next pack update, the rest will be fixed with the next map update at the beginning of December.
