### ISSUE TITLE
we need an hero bug

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#96]
## Description
after finding the sewers in fornost the quest has the entity chest doesnt give you the artifact.
## Base information
* Minecraft version:1.12.2
* Minecraft Forge version:14.23.5.2847
* TolkienCraft II version:1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Looks like this quest was another victim of the book update from 1.10 to 1.12.  it was still marked as auto claim but was using the old version of autoClaim and did not convert to autoclaim.  It is fixed and should be in the next pack update here in a few days.
