### ISSUE TITLE
rider of plains

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#98]
## Description
after talking with Dolin Foebreaker after completing the quest "wargish threat" the next quest "riders of plain" doesn't start,a temporary fix is to add the quest "rider of plains" to the dialog "riders of plain IV" 
## Base information
* Minecraft version:1.12
* Minecraft Forge version:14.23.5.2847
* TolkienCraft II version: 1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Thank you for reporting these job board quest issues...this one will also be corrected in the next pack update.
