### ISSUE TITLE
rivendell forging 

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#99]
## Description
after talking with the elven smith in imladris during the quest "reforging sword" a scene called imladris reforging should "start" but it doesnt.

## Base information
* Minecraft version:1.12.2
* Minecraft Forge version:14.23.5.2847
* TolkienCraft II version:1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
So the work-around should be type /noppes scene reset CastienStart

then type /noppes scene start CastienStart

This should make it process for you.

Tested in my dev map and it triggers fine, so not sure why it did not for you.
